name: Update PR Description

on:
  pull_request:
    types:
      - synchronize
  push:
    branches:
      - '**' # Replace with the branch name(s) you want to trigger on

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3 

      - name: Fetch Commit Messages
        id: commits
        run: |
          BRANCH_NAME=${{ github.ref }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          COMMITS=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/${{ github.repository }}/commits?sha=$BRANCH_NAME" | jq -r '.[].commit.message')
          echo "::set-output name=commit-messages::$COMMITS"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update PR Description
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const commitMessages = core.getInput('commit-messages');
            const issueReferences = [];
            const regex = /manoharup03\/skills-test-with-actions\/issues\/(\d+)/g;
            const matches = commitMessages.match(regex);
            if (matches) {
              issueReferences.push(...matches.map(match => `manoharup03/skills-test-with-actions/issues/${match.split("/")[1]}`));
            }

            const pr = await github.pulls.get({
              owner,
              repo,
              pull_number: prNumber,
            });

            const currentDescription = pr.data.body || '';
            const newDescription = `${currentDescription}\n\nIssue references: ${issueReferences.join(', ')}`;

            await github.pulls.update({
              owner,
              repo,
              pull_number: prNumber,
              body: newDescription,
            });
