name: Update PR Body

on:
  pull_request:
    types:
      - synchronize
  push:
    branches:
      - beta
      - main

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - name: Update PR Body
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const octokit = require('@octokit/rest')();
            octokit.authenticate({
                type: 'token',
                token: process.env.GITHUB_TOKEN,
            });

            // Fetch commit messages to extract issue numbers
            const commits = await octokit.pulls.listCommits({
                owner: owner,
                repo: repo,
                pull_number: prNumber,
            });

            const issueNumbers = new Set();
            const issueRegex = /manoharup03\/skills-test-with-actions\/issues\/(\d+)/g;

            commits.data.forEach(commit => {
                const message = commit.commit.message;
                const matches = message.match(issueRegex);

                if (matches) {
                    matches.forEach(match => {
                        // Extract the issue number and add it to the Set
                        issueNumbers.add(match);
                    });
                }
            });

            // Generate the body with a list of issue references
            const issueNumbersList = Array.from(issueNumbers);
            const issueReferences = issueNumbersList.map(issueNumber => `- fixes ${issueNumber}`).join('\n');

            // Update the PR body
            const prUpdateData = {
                owner: owner,
                repo: repo,
                pull_number: prNumber,
                body: issueReferences,
            };

            await octokit.pulls.update(prUpdateData);
